<a href="https://colab.research.google.com/github/luismiguelcasadodiaz/IBM_SkillsBuild_IA_325/blob/main/IA_325_py_ex_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio 2 de pandes 8 del curso
Creamos un dataframe con las ventas de las tres oficinas para los tres primeros meses del año

In [2]:
import numpy as np
import pandas as pd

In [4]:
ventas_ene = np.random.randint(100, 500, 3)
ventas_ene

array([421, 169, 344])

In [5]:
ventas_feb = np.random.randint(100, 500, 3)
ventas_feb

array([279, 346, 162])

In [6]:
ventas_mar = np.random.randint(100, 500, 3)
ventas_mar

array([452, 421, 484])

In [7]:
filas = ["ene", "feb", "mar"]
columnas = ["of1", "of2", "of3"]
datos = [ventas_ene, ventas_feb, ventas_mar]

In [11]:
df = pd.DataFrame(datos, index=filas, columns=columnas)
df

of1  of2  of3
ene  421  169  344
feb  279  346  162
mar  452  421  484

In [12]:
# Mediante Print muestra el valor de las ventas de enero para la oficina 1
mes = 'ene'
oficina = 'of1'
dato = df.loc[mes, oficina]
print(f"Las ventas de {mes} para la oficina {oficina} son de {dato}")

Las ventas de ene para la oficina of1 son de 421
