<a href="https://colab.research.google.com/github/luismiguelcasadodiaz/IBM_SkillsBuild_IA_325/blob/main/IA_325_py_cod_ex_14_s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predecir el rendimiento de un jugador

### Enunciado del ejercicio

Imagina que formas parte del equipo de desarrollo de un videojuego multijugador competitivo. El equipo de analítica necesita predecir cuántas **victorias** podría lograr un nuevo jugador, basándose únicamente en su estilo de juego.

Como científico de datos, tu misión es crear un modelo de **regresión lineal** que pueda predecir las victorias de un jugador en función de su rendimiento medio en partidas anteriores.

Para organizar bien tu solución y facilitar su reutilización en el futuro, deberás construirla utilizando tres clases bien definidas.

### Lo que debes hacer

1. Crea la clase Player.Representa a un jugador. Debe contener:
+ atributos
  + name: nombre del jugador

  + avg_session_time: duración promedio de sus sesiones de juego (en minutos)

  + avg_actions_per_min: acciones por minuto que realiza

  + avg_kills_per_session: número promedio de eliminaciones por sesión

  + victories: número de victorias (opcional, ya que puede usarse para predicción)
+ métodos
  + to_features(self) que devuelva una lista con los valores de entrada para el modelo.
  <br>
  <br>

2. Crea la clase PlayerDataset. Representa una colección de jugadores. Debe tener:
+ Métodos

  + Un constructor que reciba una lista de objetos Player

  + Un método get_feature_matrix() que devuelva una lista de listas con los valores de entrada (X)

  + Un método get_target_vector() que devuelva una lista con los valores objetivo (y, las victorias)
<br>
<br>

3. Crea la clase VictoryPredictor Encargada de entrenar y usar el modelo de regresión. Debe contener:
+ Atributos:
  + Un atributo con el modelo (LinearRegression)
+ Metodos:
  + Un método train(dataset: PlayerDataset) para entrenar el modelo con los datos del dataset

  + Un método predict(player: Player) que devuelva el número de victorias predichas para ese jugador


### Ejemplo de uso
```python
players = [
    Player("Alice", 40, 50, 6, 20),
    Player("Bob", 30, 35, 4, 10),
    Player("Charlie", 50, 60, 7, 25),
    Player("Diana", 20, 25, 2, 5),
    Player("Eve", 60, 70, 8, 30)
]

dataset = PlayerDataset(players)
predictor = VictoryPredictor()
predictor.train(dataset)

test_player = Player("TestPlayer", 45, 55, 5)
predicted = predictor.predict(test_player)
print(f"Victorias predichas para {test_player.name}: {predicted:.2f}")
```

### Salida esperada

Victorias predichas para TestPlayer: 22.50



## Creación de la clase Player

In [47]:
class Player:
  def __init__(self, name, avg_session_time, avg_actions_per_min, avg_kills_per_session, victories=None):
      """
      Inicializa una nueva instancia de la clase Player.

      :param name: str - Nombre del jugador.
      :param avg_session_time: float - Duración promedio de las sesiones en minutos.
      :param avg_actions_per_min: float - Acciones por minuto.
      :param avg_kills_per_session: float - Eliminaciones promedio por sesión.
      :param victories: int, optional - Número de victorias.
      """
      self.name = name
      self.avg_session_time = avg_session_time
      self.avg_actions_per_min = avg_actions_per_min
      self.avg_kills_per_session = avg_kills_per_session
      self.victories = victories

  def to_features(self):
      """
      Devuelve una lista con las características del jugador utilizadas como entrada para un modelo predictivo.

      :return: list[float] - Características: [avg_session_time, avg_actions_per_min, avg_kills_per_session]
      """
      return [
          self.avg_session_time,
          self.avg_actions_per_min,
          self.avg_kills_per_session
      ]

#### Test para la clase player

In [48]:
import numpy as np
player1 = Player("Luis", 45.5, 120.0, 15.2, victories=12)
print(f"Las caracteristicas de {player1.name} son {player1.to_features()}")  # Salida: [45.5, 120.0, 15.2]
fila =np.array(player1.to_features())
print(fila)
print(type(fila))
print(fila.shape)
#The elements of the shape tuple give the lengths of the corresponding array dimensions.
#(4,) array unidimensional con 4 elementos

columna = fila.reshape(1, -1) #transforma el unidimensional en bidimendional con 1 sola fila y las columnas necesarios
print(columna)
print(type(columna))
print(columna.shape)
#(1,4) array bidimensional con 1 fila y 4 columnas
print(np.array(player1.to_features()).reshape(1, -1))

Las caracteristicas de Luis son [45.5, 120.0, 15.2]
[ 45.5 120.   15.2]
<class 'numpy.ndarray'>
(3,)
[[ 45.5 120.   15.2]]
<class 'numpy.ndarray'>
(1, 3)
[[ 45.5 120.   15.2]]


## Creación de la clase PlayerDataset

In [49]:
class PlayerDataset:
  def __init__(self, players):
      """
      Inicializa una instancia de PlayerDataset con una lista de objetos Player.

      :param players: list[Player] - Lista de jugadores.
      """
      self.players = players

  def get_feature_matrix(self):
      """
      Devuelve una matriz de características (X), compuesta por listas con las características de cada jugador.

      :return: list[list[float]] - Matriz de características.
      """
      return [player.to_features() for player in self.players]

  def get_target_vector(self):
      """
      Devuelve un vector de etiquetas objetivo (y), correspondiente a las victorias de cada jugador.

      :return: list[int] - Vector de objetivos (victorias). Jugadores sin victorias son excluidos.
      """
      return [player.victories for player in self.players if player.victories is not None]


#### Test para la clase PlayerDataset

In [50]:
players = [
    Player("Luis", 45.5, 120.0, 15.2, victories=12),
    Player("Ana", 30.0, 100.0, 10.5, victories=8),
    Player("Carlos", 60.0, 140.0, 20.0)  # Sin victorias conocidas
]

dataset = PlayerDataset(players)

X = dataset.get_feature_matrix()
y = dataset.get_target_vector()

print("Matriz de características (X):", X)
print("Vector de objetivos (y):", y)

Matriz de características (X): [[45.5, 120.0, 15.2], [30.0, 100.0, 10.5], [60.0, 140.0, 20.0]]
Vector de objetivos (y): [12, 8]


## Creación de la clase VictoryPredictor

In [51]:
from sklearn.linear_model import LinearRegression
import numpy as np

class VictoryPredictor:
  def __init__(self):
      """
      Inicializa el predictor con un modelo de regresión lineal.
      """
      self.model = LinearRegression()

  def train(self, dataset):
      """
      Entrena el modelo usando los datos proporcionados en un objeto PlayerDataset.

      :param dataset: PlayerDataset - Dataset de jugadores con características y valores objetivo.
      """
      X = dataset.get_feature_matrix()
      y = dataset.get_target_vector()
      self.model.fit(X, y)

  def predict(self, player):
      """
      Predice el número de victorias para un jugador individual.

      :param player: Player - Jugador para el cual se desea predecir el número de victorias.
      :return: float - Número predicho de victorias.
      """
      X_new = np.array(player.to_features()).reshape(1, -1)
      prediction = self.model.predict(X_new)
      return prediction[0]


In [52]:
players = [
    Player("Alice", 40, 50, 6, 20),
    Player("Bob", 30, 35, 4, 10),
    Player("Charlie", 50, 60, 7, 25),
    Player("Diana", 20, 25, 2, 5),
    Player("Eve", 60, 70, 8, 30)
]

dataset = PlayerDataset(players)
predictor = VictoryPredictor()
predictor.train(dataset)

test_player = Player("TestPlayer", 45, 55, 5)
predicted = predictor.predict(test_player)
print(f"Victorias predichas para {test_player.name}: {predicted:.2f}")

Victorias predichas para TestPlayer: 22.50
