<a href="https://colab.research.google.com/github/luismiguelcasadodiaz/IBM_SkillsBuild_IA_325/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Crear un array a partir de una lista

In [6]:
import numpy as np

In [7]:
lista = [1,2,3,4]
array = np.array(lista)

array

array([1, 2, 3, 4])

In [8]:
lista2 = [ [1, 2, 3], [4, 5, 6], [7, 8, 9] ]
array2 = np.array(lista2)

In [11]:

print(array)
print("-----")
print(array2)

[1 2 3 4]
-----
[[1 2 3]
 [4 5 6]
 [7 8 9]]


crear un array con uns secuencia de números creados con arange()

In [12]:
multiplos_5 = np.arange(5,55, 5)
print(multiplos_5)

[ 5 10 15 20 25 30 35 40 45 50]


Crear vectores o matrices nulas con la funcion zeros()

In [16]:
vector_5_nulo=np.zeros(5)
matriz_3_x_6_nulo=np.zeros((3,6))

In [17]:
print(vector_5_nulo)
print("-----")
print(matriz_3_x_6_nulo)

[0. 0. 0. 0. 0.]
-----
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Crear vectores o matrices unitarias con la funcion ones()

In [18]:
vector_5_unitario=np.ones(5)
matriz_6_x_3_unitario=np.ones((6,3))

In [19]:
print(vector_5_unitario)
print("-----")
print(matriz_6_x_3_unitario)

[1. 1. 1. 1. 1.]
-----
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Crear vectores con un determinado número de elementos equidistantes entre un limite inferior y uno superieor

In [23]:
secuencia = np.linspace(1,2,9)
print(secuencia)

[1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.   ]


Crea la matriz identidad (Diagonal principal con unos)

In [24]:
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Crear vectores y matrices de numeros aleatorios

In [34]:
# rand genera aleatorios ente 0 y 1
vector_aleatorio = np.random.rand(5)
matriz_aleatoria = np.random.rand(3,5)
print(vector_aleatorio)
print("-----")
print(matriz_aleatoria)

[0.21886072 0.69764001 0.40248169 0.80601967 0.61543968]
-----
[[0.31014964 0.7549965  0.29629256 0.21288267 0.58845652]
 [0.14092961 0.83483755 0.58415554 0.37154867 0.74988837]
 [0.75733058 0.22895998 0.99195544 0.48145649 0.74050176]]


In [35]:
print(vector_aleatorio.mean())

0.5480883540285955


In [36]:
# randn genera aleatorios siguiendo una distribución normal standard (media = 0, dev_std = 1)
vector_aleatorio = np.random.randn(5)
matriz_aleatoria = np.random.randn(3,5)
print(vector_aleatorio)
print("-----")
print(matriz_aleatoria)

[-0.0229323   0.07723095  1.14825798 -0.99068941  0.43188962]
-----
[[-0.1681834   1.24100349  1.470457   -0.19960641  0.76984745]
 [ 0.33779876  0.86267535 -2.10098465 -2.20286944 -0.44595427]
 [ 0.18574653 -1.30997046  0.97624179 -0.93901293  0.99973543]]


In [37]:
print(vector_aleatorio.mean())

0.12875137104889298


Crear vectores y matrices de numeros aleatorios enteros

In [39]:
vector_5_aleatorios_enteros_entre_1_y_100 = np.random.randint(1,100,5)
print(vector_5_aleatorios_enteros_entre_1_y_100)

[79 60 91 10 12]


Cambio del tamaño de un vector o una matrix

In [40]:
array = np.random.randint(1,100,20)
print(array)

[28 43 89 69 50 93 72 94 80 13 73 38 22 95 43 88 62 33  3 58]


In [41]:
matriz = array.reshape(4,5)

In [42]:
print(matriz)

[[28 43 89 69 50]
 [93 72 94 80 13]
 [73 38 22 95 43]
 [88 62 33  3 58]]


Calcular el máximo y el minimo de un *vector* y su posicion

In [3]:
# prompt: 10 random numbers using numpy

import numpy as np

random_numbers = np.random.randint(0, 100, 10) # Generates 10 random integers between 0 and 99 (inclusive)
random_numbers
valr_maximo = random_numbers.max()
posicion_maximo = random_numbers.argmax()
valr_minimo = random_numbers.min()
posicion_minimo = random_numbers.argmin()
print(random_numbers)
print(valr_maximo)
print(posicion_maximo)
print(valr_minimo)
print(posicion_minimo)


[97 14 43 29 34  0 40 67 94 86]
97
0
0
5


Acceso a los elementos de los vectores

In [5]:
print(f"El primer elemento del array es {random_numbers[0]}")
print(f"El segundo elemento del array es {random_numbers[1]}")
print(f"el ultimo elemento del array es {random_numbers[-1]}")
print(f"Los elementos del segundo al cuarto elemento del array son {random_numbers[1:4]}")
print(f"Los elementos del inicio al tercer elemento del array son {random_numbers[:3]}")
print(f"Los elementos del quinto al final del array son {random_numbers[4:]}")


El primer elemento del array es 97
El segundo elemento del array es 14
el ultimo elemento del array es 86
Los elementos del segundo al cuarto elemento del array son [14 43 29]
Los elementos del inicio al tercer elemento del array son [97 14 43]
Los elementos del quinto al final del array son [34  0 40 67 94 86]


Copiar un array

In [9]:
copia_array = random_numbers.copy()
print(copia_array)
print(f"La dirección de memoria del array es {hex(id(random_numbers))}")
print(f"La dirección de memoria de la copia del array es {hex(id(copia_array))} ")
random_numbers[0] = 100
print(f"La dirección de memoria del array es {hex(id(random_numbers))}")
print(f"La dirección de memoria de la copia del array es {hex(id(copia_array))} ")
print(f"El primer elemento del array es {random_numbers[0]}")
print(f"El primer elemento de la copia del array es {copia_array[0]}")

[97 14 43 29 34  0 40 67 94 86]
La dirección de memoria del array es 0x781af84f3bd0
La dirección de memoria de la copia del array es 0x781acfe86fd0 
La dirección de memoria del array es 0x781af84f3bd0
La dirección de memoria de la copia del array es 0x781acfe86fd0 
El primer elemento del array es 100
El primer elemento de la copia del array es 97


Acceso a los elementos de una matriz

In [12]:
matriz = np.array([[1, 2, 3],[4, 5 ,6],[7, 8, 9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:

print(f"El primer elemento de la matriz es {matriz[0][0]}")
print(f"El ultimo elemento de la matriz es {matriz[-1][-1]}")
print(f"Los elementos de la segunda fila de la matriz son {matriz[1]}")
print(f"Los elementos de la segunda columna de la matriz son {matriz[:,1]}")
print(f"Los elementos de la segunda y tercera fila de la matriz son {matriz[1:3]}")
print(f"Los elementos de la segunda y tercera fila y segunda y tercera columna de la matriz son {matriz[1:3,1:3]}")


El primer elemento de la matriz es 1
El ultimo elemento de la matriz es 9
Los elementos de la segunda fila de la matriz son [4 5 6]
Los elementos de la segunda columna de la matriz son [2 5 8]
Los elementos de la segunda y tercera fila de la matriz son [[4 5 6]
 [7 8 9]]
Los elementos de la segunda y tercera fila y segunda y tercera columna de la matriz son [[5 6]
 [8 9]]


Seleccionar los elementos de una vector que cumplen una condición

In [14]:
datos = np.arange(0,20)
datos

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
condicion_par = datos % 2 == 0
condicion_impar = datos % 2 != 0
print(condicion_par)

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False]


In [20]:
pares = datos[condicion_par]
impares = datos[condicion_impar]
print(pares)
print(impares)

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]


Operaciones aritmeticas con arrays

In [21]:
print(datos * 100)
print(datos + 100)
print(datos / 100)
print(datos - 100)
print(datos + datos)
print(datos - datos)
print(datos * datos)
print(datos / datos)

[   0  100  200  300  400  500  600  700  800  900 1000 1100 1200 1300
 1400 1500 1600 1700 1800 1900]
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]
[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.]


<ipython-input-21-833830eaed23>:8: RuntimeWarning: invalid value encountered in divide
  print(datos / datos)


Funciones aplicadas a los arrays

In [24]:
print(f"Raiz cuadrada {np.sqrt(datos)}")
print(f"Exponencial {np.exp(datos)}")
print(f"Logaritmo {np.log(datos)}")
print(f"Media {np.mean(datos)}")
print(f"Desviación estándar {np.std(datos)}")
print(f"Suma {np.sum(datos)}")
print(f"Suma acumulada {np.cumsum(datos)}")
print(f"Suma acumulada {np.cumsum(datos)}")

Raiz cuadrada [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894]
Exponencial [1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06
 8.88611052e+06 2.41549528e+07 6.56599691e+07 1.78482301e+08]
Logaritmo [      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527
 2.48490665 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334
 2.89037176 2.94443898]
Media 9.5
Desviación estándar 5.766281297335398
Suma 190
Suma acumulada [  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153
 171 190]
Suma acumulada [  0   1   3   6  10  15  21  28  36  

<ipython-input-24-245b97bead92>:3: RuntimeWarning: divide by zero encountered in log
  print(f"Logaritmo {np.log(datos)}")
